version: '2'

services:

  seleniumtests:
    image: "node:6"
    environment:
      - "MW_SERVER=http://web"
      - "MW_SCRIPT_PATH=/mediawiki"
      - "MEDIAWIKI_USER=selenium"
      - "MEDIAWIKI_PASSWORD=test1234"
    command: echo 'invoke me through ./browsertest'
    working_dir: /app
    volumes:
      - "${DOCKER_MW_PATH}:/app"
      - "${EXT_ADVANCEDSEARCH_PATH}:/app/extensions/AdvancedSearch"
      - "${EXT_WIKIBASE_PATH}:/app/extensions/Wikibase"
      - "${EXT_WIKIBASELEXEME_PATH}:/app/extensions/WikibaseLexeme"
      - "${SELENIUM_LOG_PATH}:/app/log"
    depends_on:
      - selenium

  selenium:
    image: selenium/standalone-chrome
    shm_size: '2gb'
    depends_on:
      - web
