version: '2'

services:
  web:
    # additional volumes (https://docs.docker.com/compose/extends/#adding-and-overriding-configuration)
    volumes:
      - "${EXT_ADVANCEDSEARCH_PATH}:/var/www/mediawiki/extensions/AdvancedSearch"
      - "${EXT_CIRRUSSEARCH_PATH}:/var/www/mediawiki/extensions/CirrusSearch"
      - "${EXT_ELASTICA_PATH}:/var/www/mediawiki/extensions/Elastica"
      - "${EXT_EVENTLOGGING_PATH}:/var/www/mediawiki/extensions/EventLogging"
    depends_on:
      - elasticsearch

  phpmyadmin:
    image: hello-world

  graphite-statsd:
    image: hello-world

  # to update indexes
  # docker-compose ... run web php /var/www/mediawiki/extensions/CirrusSearch/maintenance/updateSearchIndexConfig.php
  # docker-compose ... run web php /var/www/mediawiki/extensions/CirrusSearch/maintenance/forceSearchIndex.php
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.0
    environment:
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
